FROM python:3.10-slim

RUN apt -y update && \
    apt -y upgrade && \
    apt install -y ffmpeg

WORKDIR /app

RUN python -m pip install --upgrade pip

COPY ./requirements.txt . 
 
RUN pip3 install -r /app/requirements.txt --no-cache-dir 
 
COPY . . 
 
CMD ["gunicorn", "vrc.wsgi:application", "--bind", "0:8000" ]
